### ISSUE TITLE
Unable to stop activity MoviesActivity. Missing event handler for an annotated method.

### ISSUE THREAD

**Issue by semenoh** [saulmm/Material-Movies#1]
```
02-05 13:54:35.372      890-890/com.hackvg.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.hackvg.android, PID: 890
    java.lang.RuntimeException: Unable to stop activity {com.hackvg.android/com.hackvg.android.views.activities.MoviesActivity}: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class com.hackvg.android.mvp.presenters.PopularShowsPresenterImpl registered?
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
            at android.app.ActivityThread.access$1100(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class com.hackvg.android.mvp.presenters.PopularShowsPresenterImpl registered?
            at com.squareup.otto.Bus.unregister(Bus.java:289)
            at com.hackvg.android.mvp.presenters.PopularShowsPresenterImpl.onStop(PopularShowsPresenterImpl.java:35)
            at com.hackvg.android.views.activities.MoviesActivity.onStop(MoviesActivity.java:84)
            at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1261)
            at android.app.Activity.performStop(Activity.java:6085)
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3341)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
            at android.app.ActivityThread.access$1100(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by EarlOfEgo** [comment]
In the presenters onCreate is used to register them to the otto bus and onStop to unregister.
That's fine, but calling *Presenter.onCreate in an Activities `onCreate()` method to register can lead into an exception when you unregister your *Presenter in the `onStop()` method.
This is the case if the Activity goes to the background(onStop is called) comes back to the foreground and then goes again back into the background(onStop is called a second time as well as unregister)
![Lifecycle](http://developer.android.com/images/activity_lifecycle.png)

So it would be better to call register in `onStart()`

**Comment by saulmm** [comment]
@EarlOfEgo you are right, I just merged, thanks!
