### ISSUE TITLE
Crashes when rotating 

### ISSUE THREAD

**Issue by MiguelCatalan** [saulmm/Material-Movies#26]
07-23 15:45:18.031  11884-11884/com.hackvg.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.hackvg.android, PID: 11884
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hackvg.android/com.hackvg.android.views.activities.MoviesActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.hackvg.android.mvp.views.MoviesView.isTheListEmpty()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3941)
            at android.app.ActivityThread.access$1000(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by Fshamri** [comment]
have you found a solution for this?
